// synonyms.js

export default {
  // Amoxicillin + Clavulanic Acid
  "augmentin": "amoxicillinclavulanic",
  "augmentine": "amoxicillinclavulanic",
  "amoksiklav": "amoxicillinclavulanic",
  "coamoxiclav": "amoxicillinclavulanic",
  "amoxclav": "amoxicillinclavulanic",
  "amoxycillinclav": "amoxicillinclavulanic",

  // Amoxicillin
  "amoxil": "amoxicillin",
  "amox": "amoxicillin",
  "amoxicillin": "amoxicillin",

  // Ciprofloxacin
  "cipro": "ciprofloxacin",
  "ciproxin": "ciprofloxacin",
  "ciprodex": "ciprofloxacin",
  "ciproflox": "ciprofloxacin",

  // Azithromycin
  "zithromax": "azithromycin",
  "azithro": "azithromycin",
  "azit": "azithromycin",
  "azithromycin": "azithromycin",

  // Metronidazole
  "flagyl": "metronidazole",
  "metro": "metronidazole",
  "metrogyl": "metronidazole",
  "metronidazole": "metronidazole",

  // Clindamycin
  "dalacin": "clindamycin",
  "clinda": "clindamycin",
  "clindamycin": "clindamycin",

  // Cephalosporins
  "zinnat": "cefuroxime",
  "cefurox": "cefuroxime",
  "cefur": "cefuroxime",
  "omnicef": "cefdinir",
  "cefdinir": "cefdinir",
  "cefixime": "cefixime",
  "suprax": "cefixime",
  "ceftriax": "ceftriaxone",
  "ceftriaxone": "ceftriaxone",
  "cefotax": "cefotaxime",
  "cefotaxime": "cefotaxime",

  // Malaria
  "lonart": "artemetherlumefantrine",
  "coartem": "artemetherlumefantrine",
  "p-alaxin": "artemetherlumefantrine",
  "malafin": "artemetherlumefantrine",
  "act": "artemisininbasedcombinationtherapy",
  "artemether": "artemether",
  "lumefantrine": "lumefantrine",
  "quine": "quinine",
  "chloroquine": "chloroquine",
  "cq": "chloroquine",

  // Painkillers
  "panadol": "paracetamol",
  "tylenol": "paracetamol",
  "pcm": "paracetamol",
  "paracetamol": "paracetamol",
  "acetaminophen": "paracetamol",
  "aspirin": "aspirin",
  "asa": "aspirin",
  "voltaren": "diclofenac",
  "diclo": "diclofenac",
  "diclofenac": "diclofenac",
  "motrin": "ibuprofen",
  "advil": "ibuprofen",
  "nurofen": "ibuprofen",
  "ibu": "ibuprofen",
  "ibuprofen": "ibuprofen",

  // Cold & Allergy
  "piriton": "chlorpheniramine",
  "chlorphen": "chlorpheniramine",
  "chlorpheniramine": "chlorpheniramine",
  "claritin": "loratadine",
  "loratadine": "loratadine",
  "loraditine": "loratadine",
  "cetirizine": "cetirizine",
  "zyrtec": "cetirizine",
  "ctz": "cetirizine",
  "benadryl": "diphenhydramine",
  "diphenhydramine": "diphenhydramine",
  "promethazine": "promethazine",
  "phenergan": "promethazine",

  // Gastric
  "omeprazole": "omeprazole",
  "prilosec": "omeprazole",
  "esomeprazole": "esomeprazole",
  "nexium": "esomeprazole",
  "pantoprazole": "pantoprazole",
  "protonix": "pantoprazole",
  "ranitidine": "ranitidine",
  "zantac": "ranitidine",
  "cimetidine": "cimetidine",
  "tagamet": "cimetidine",

  // Vitamins
  "vitc": "vitaminc",
  "vitamin c": "vitaminc",
  "ascorbic": "vitaminc",
  "vitd": "vitamind",
  "vitamin d": "vitamind",
  "folic": "folicacid",
  "folate": "folicacid",
  "folicacid": "folicacid",
  "ferrous": "iron",
  "iron": "iron",
  "ferrous sulfate": "iron",
  "chemiron": "iron",
  "hematinic": "iron",
  "bcomplex": "bcomplex",
  "multivitamin": "multivitamin",
  "multivite": "multivitamin",

  // Common tests
  "hvs": "highvaginalswab",
  "mcs": "microscopyculturesensitivity",
  "hvs mcs": "highvaginalswabmicroscopyculturesensitivity",
  "urine mcs": "urinemicroscopyculturesensitivity",
  "fbc": "fullbloodcount",
  "cbc": "completebloodcount",
  "rbs": "randombloodsugar",
  "fbs": "fastingbloodsugar",
  "ppbs": "postprandialbloodsugar",
  "hba1c": "glycatedhemoglobin",
  "ppd": "purifiedproteinderivative",
  "mantoux": "mantouxtest",
  "mantox": "mantouxtest",

  // Dosage forms
  "tab": "tablet",
  "tabs": "tablet",
  "tab.": "tablet",
  "inj": "injection",
  "inj.": "injection",
  "injec": "injection",
  "injs": "injection",
  "cap": "capsule",
  "caps": "capsule",
  "cap.": "capsule",
  "syr": "syrup",
  "syr.": "syrup",
  "susp": "suspension",
  "susp.": "suspension",
  "amp": "ampoule",
  "vial": "vial",
  "cream": "cream",
  "ointment": "ointment",
  "soln": "solution",
  "solution": "solution",
  "drops": "drops",
  "drp": "drops",
  "drps": "drops",

  // Units
  "mg": "milligram",
  "ml": "millilitre",
  "gm": "gram",
  "gr": "gram",
  "mcg": "microgram",
  "iu": "internationalunits",

  // More extra real life mixups
  "dxm": "dextromethorphan",
  "ors": "oralrehydrationsalts",
  "ivf": "intravenousfluids",
  "saline": "normal saline",
  "ns": "normal saline",
  "rtk": "rapidtestkit",
  "acth": "adrenocorticotropichormone",
  "hct": "hydrochlorothiazide",
  "mtx": "methotrexate",
  "dex": "dexamethasone",
  "epo": "erythropoietin",
};
