const synonyms = new Map([
  ["augmentin", "amoxicillinclavulanic"],
  ["amoksiklav", "amoxicillinclavulanic"],
  ["amoxclav", "amoxicillinclavulanic"],
  ["amoxil", "amoxicillin"],
  ['amoxyl','amoxicillin'],
  ["coamoxiclav", "amoxicillinclavulanic"],
  ["cipro", "ciprofloxacin"],
  ["ciprodex", "ciprofloxacin"],
  ["zinnat", "cefuroxime"],
  ["omnicef", "cefdinir"],
  ["flagyl", "metronidazole"],
  ["tinidazole", "tinidazole"],
  ["zoladex", "goserelin"],
  ["augmentine", "amoxicillinclavulanic"],
  ["panadol", "paracetamol"],
  ["tylenol", "paracetamol"],
  ["paracetamol", "paracetamol"],
  ["acetaminophen", "paracetamol"],
  ["voltaren", "diclofenac"],
  ["diclo", "diclofenac"],
  ['ats','Antitetanusserum'],
  ["motrin", "ibuprofen"],
  ["advil", "ibuprofen"],
  ["neurofen", "ibuprofen"],
  ["ibuprofen", "ibuprofen"],
  ["metro", "metronidazole"],
  ["zithromax", "azithromycin"],
  ["azithro", "azithromycin"],
  ["aricept", "donepezil"],
  ["avlox", "moxifloxacin"],
  ["avelox", "moxifloxacin"],
  ["levoxin", "levofloxacin"],
  ["levaquin", "levofloxacin"],
  ["piriton", "chlorpheniramine"],
  ["claritin", "loratadine"],
  ["cetirizine", "cetirizine"],
  ["zyrtec", "cetirizine"],
  ["clomid", "clomiphene"],
  ["clomiphene", "clomiphene"],
  ["benadryl", "diphenhydramine"],
  ["ciproxin", "ciprofloxacin"],
  ["tab", "tablet"],
  ["tabs", "tablet"],
  ["inj", "injection"],
  ["cap", "capsule"],
  ["caps", "capsule"],
  ["syrub", "syrup"],
  ["syr", "syrup"],
  ["susp", "suspension"],
  ["amp", "ampoule"],
  ["vial", "vial"],
  ["cream", "cream"],
  ["ointment", "ointment"],
  ["soln", "solution"],
  ["sol", "solution"],
  ["mg", "milligram"],
  ["ml", "millilitre"],
  ["gm", "gram"],
  ["gr", "gram"],
  ["pdr", "powder"],
  ["pdrs", "powder"],
  ["drp", "drops"],
  ["drps", "drops"],
  ["forte", "forte"],
  ["xr", "extended release"],
  ["sr", "sustained release"],
  ["er", "extended release"],
  ["inj.", "injection"],
  ["tab.", "tablet"],
  ["cap.", "capsule"],
  ["syr.", "syrup"],
  ["injec", "injection"],
  ["clav", "clavulanic"],
  ["hcv", "hepatitis c virus"],
  ["hbv", "hepatitis b virus"],
  ["hiv", "human immunodeficiency virus"],
  ["act", "artemisinin-based combination therapy"],
  ["tb", "tuberculosis"],
  ["mdr-tb", "multi-drug resistant tuberculosis"],
  ["xdr-tb", "extensively drug-resistant tuberculosis"],
  ["dots", "directly observed treatment short-course"],
  ["rti", "respiratory tract infection"],
  ["uti", "urinary tract infection"],
  ["sti", "sexually transmitted infection"],
  ["ari", "acute respiratory infection"],
  ["chd", "coronary heart disease"],
  ["cad", "coronary artery disease"],
  ["copd", "chronic obstructive pulmonary disease"],
  ["dm", "diabetes mellitus"],
  ["htn", "hypertension"],
  ["chf", "congestive heart failure"],
  ["ihd", "ischemic heart disease"],
  ["ckd", "chronic kidney disease"],
  ["esrd", "end-stage renal disease"],
  ["cns", "central nervous system"],
  ["pns", "peripheral nervous system"],
  ["gi", "gastrointestinal"],
  ["gu", "genitourinary"],
  ["ent", "ear nose throat"],
  ["cxr", "chest x-ray"],
  ["mri", "magnetic resonance imaging"],
  ["ct", "computed tomography"],
  ["ecg", "electrocardiogram"],
  ["eeg", "electroencephalogram"],
  ["lft", "liver function test"],
  ["rft", "renal function test"],
  ["fbs", "fasting blood sugar"],
  ["ppbs", "postprandial blood sugar"],
  ["hba1c", "glycated hemoglobin"],
  ["inr", "international normalized ratio"],
  ["ppd", "purified protein derivative"],
  ["vdrl", "venereal disease research laboratory"],
  ["rpr", "rapid plasma reagin"],
  ["hbsag", "hepatitis b surface antigen"],
  ["hbeag", "hepatitis b e antigen"],
  ["hcv ab", "hepatitis c antibody"],
  ["hiv ab", "hiv antibody"],
  ["hiv ag", "hiv antigen"],
  ["att", "anti-tubercular therapy"],
  ["acth", "adrenocorticotropic hormone"],
  ["pco", "polycystic ovary syndrome"],
  ["pid", "pelvic inflammatory disease"],
  ["iud", "intrauterine device"],
  ["ivf", "in vitro fertilization"],
  ["ats", "anti-tetanus serum"],
  ["caf", "caffeine"],
  ["pcm", "paracetamol"],
  ["asa", "aspirin"],
  ["ppi", "proton pump inhibitor"],
  ["ocp", "oral contraceptive pill"],
  ["bcg", "bacillus calmette–guérin vaccine"],
  ["dtp", "diphtheria tetanus pertussis vaccine"],
  ["art", "anti-retroviral therapy"],
  ["arv", "anti-retroviral"],
  ["inh", "isoniazid"],
  ["rif", "rifampicin"],
  ["azt", "zidovudine"],
  ["hct", "hydrochlorothiazide"],
  ["ctz", "cetirizine"],
  ["dxm", "dextromethorphan"],
  ["dex", "dexamethasone"],
  ["ivf", "intravenous fluids"],
  ["ors", "oral rehydration salts"],
  ["ivig", "intravenous immunoglobulin"],
  ["vit c", "vitamin c"],
  ["vit d", "vitamin d"],
  ["mtx", "methotrexate"],
  ["atc", "anti-tussive & cold"],
  ["nsaid", "non-steroidal anti-inflammatory drug"],
  ["apap", "acetaminophen"],
  ["nitro", "nitroglycerin"],
  ["acb", "anti-cholinergic bronchodilator"],
  ["hrt", "hormone replacement therapy"],
  ["t3", "liothyronine"],
  ["t4", "levothyroxine"],
  ["epo", "erythropoietin"],
  ['amp','ampoule'],
  ["g-csf", "granulocyte colony stimulating factor"],
  ["lhrh", "luteinizing hormone releasing hormone"],
  ["hgh", "human growth hormone"],
  ["bcp", "birth control pill"],
  ["bzd", "benzodiazepine"],
  ["ssri", "selective serotonin reuptake inhibitor"],
  ["snri", "serotonin norepinephrine reuptake inhibitor"],
  ["tca", "tricyclic antidepressant"],
  ["aed", "anti-epileptic drug"],
  ["pth", "parathyroid hormone"],
  ["cs", "corticosteroid"],
  ["vzig", "varicella zoster immune globulin"],
  ["mmr", "measles mumps rubella vaccine"],
  ["tdap", "tetanus diphtheria pertussis vaccine"],
  ["hpv", "human papillomavirus vaccine"],
  ["rtk", "rapid test kit"],
  ["fdc", "fixed-dose combination"],
  ["oha", "oral hypoglycemic agent"],
  ["glp-1", "glucagon-like peptide-1 receptor agonist"],
  ["sglt2i", "sodium-glucose cotransporter-2 inhibitor"],
  ["acei", "angiotensin converting enzyme inhibitor"],
  ["arb", "angiotensin receptor blocker"],
  ["bb", "beta blocker"],
  ["ccb", "calcium channel blocker"],
  ["noac", "novel oral anti-coagulant"],
  ["lmwh", "low molecular weight heparin"],
  ["ufh", "unfractionated heparin"],
  ["h2ra", "h2 receptor antagonist"],
  ["tpn", "total parenteral nutrition"],
  ["ivp", "intravenous push"],
  ["po", "oral"],
  ["prn", "as needed"],
  ["bid", "twice daily"],
  ["tid", "three times daily"],
  ["qid", "four times daily"],
  ["cq", "chloroquine"],
  ["artemether", "artemether"],
  ["fbc", "full blood count"],
  ["full blood count", "full blood count"],
  ["mp", "malaria parasite test"],

  ["widal", "widal test"],
  ["pcv", "packed cell volume"],
  ["urinalysis", "urine analysis"],

  ["rvs", "retro viral screening"],
  ["hepatitisbvaccine", "hepatitisbvaccine"],
  ["hbv", "hepatitis B vaccine"],
  ["hcv", "hepatitis C virus"],
  ["vdrl", "venereal disease research laboratory"],

  ["fasting blood sugar", "fasting blood sugar"],
  ["rbs", "random blood sugar"],
  ["hvs", "high vaginal swab"],
  ["hvsmcs", "high vaginal swab microscopy culture sensitivity"],
  ["urinemcs", "urine microscopy culture sensitivity"],
  ["h.pylori", "helico bacter pylori test"],
  ["h.pyloritest", "helico bacter pylori test"],
  ["bg", "bloodglucose"],
  ["gt", "glucose tolerance test"],
  ["gtt", "glucose tolerance test"],
  ["eucr", "electrolyte sureacreatinine"],
  ["liver function test", "liverfunctiontest"],
  ["lipid profile", "lipid profile"],
  ["sfamcs", "seminal fluid analysi smicroscopy culture sensitivity"],
  ["esr", "erythrocyte sedimentation rate"],
  ["cholesterol", "cholesterol"],
  ["mantoux", "mantouxtest"],
  ["mantox", "mantouxtest"],
  ["mcs", "microscopy culture sensitivity"],
  ["afb", "acid fast bacilli"],
  ["amoxycillinclav", "amoxicillinclavulanic"],
  ["amox", "amoxicillin"],
  ["amoxicillin", "amoxicillin"],
  ["ciproflox", "ciprofloxacin"],
  ["azit", "azithromycin"],
  ["azithromycin", "azithromycin"],
  ["metrogyl", "metronidazole"],
  ["metronidazole", "metronidazole"],
  ["dalacin", "clindamycin"],
  ["clinda", "clindamycin"],
  ["clindamycin", "clindamycin"],
  ["cefurox", "cefuroxime"],
  ["cefur", "cefuroxime"],
  ["cefdinir", "cefdinir"],
  ["cefixime", "cefixime"],
  ["suprax", "cefixime"],
  ["ceftriax", "ceftriaxone"],
  ["ceftriaxone", "ceftriaxone"],
  ["cefotax", "cefotaxime"],
  ["cefotaxime", "cefotaxime"],
  ["act", "artemisinin based combination therapy"],
  ["quine", "quinine"],
  ["chloroquine", "chloroquine"],
  ["pcm", "paracetamol"],
  ["diclofenac", "diclofenac"],
  ["ibu", "ibuprofen"],
  ["chlorphen", "chlorpheniramine"],
  ["ctz", "cetirizine"],
  ["pantoprazole", "pantoprazole"],
  ["protonix", "pantoprazole"],
  ["ranitidine", "ranitidine"],
  ["zantac", "ranitidine"],
  ["cimetidine", "cimetidine"],
  ["tagamet", "cimetidine"],
  ["vitc", "vitaminc"],
  ["vitamin c", "vitamin C"],
  ["ascorbic", "vitamin C"],
  ["vitd", "vitamin D"],
  ["folic", "folicacid"],
  ["folate", "folicacid"],
  ["folicacid", "folicacid"],
  ["ferrous", "iron"],
  ["iron", "iron"],
  ["ferrous sulfate", "iron"],
  ["chemiron", "iron"],
  ["hematinic", "iron"],
  ["bcomplex", "bcomplex"],
  ["multivite", "multivitamin"],
  ["ppbs", "postprandial blood sugar"],
  ["hba1c", "glycated hemoglobin"],
  ["ppd", "purified protein derivative"],
  ["mantoux", "mantoux test"],
  ["mantox", "mantoux test"],
  ["inj.", "injection"],
  ["injs", "injection"],
  ["cap.", "capsule"],
  ["syr.", "syrup"],
  ["susp.", "suspension"],
  ["solution", "solution"],
  ["drops", "drops"],
  ["mcg", "microgram"],
  ["iu", "internationalunits"],
  ["ors", "oralrehydrationsalts"],
  ["saline", "normal saline"],
  ["ns", "normal saline"],
  ["rtk", "rapidtestkit"],
  ["acth", "adrenocorticotropichormone"],
  ["hct", "hydrochlorothiazide"],
  ["mtx", "methotrexate"],
  ["dex", "dexamethasone"],
  ["epo", "erythropoietin"],
]);

export default synonyms;
