const synonyms={
  "augmentin": "amoxicillin clavulanic",
  "amoksiklav": "amoxicillin clavulanic",
  "amoxclav": "amoxicillin clavulanic",
  "amoxil": "amoxicillin",
  "coamoxiclav": "amoxicillin clavulanic",
  "cipro": "ciprofloxacin",
  "ciprodex": "ciprofloxacin",
  "ciproxin": "ciprofloxacin",
  "zinnat": "cefuroxime",
  "omnicef": "cefdinir",
  "flagyl": "metronidazole",
  "metro": "metronidazole",
  "tinidazole": "tinidazole",
  "zoladex": "goserelin",
  "augmentine": "amoxicillin clavulanic",
  "panadol": "paracetamol",
  "tylenol": "paracetamol",
  "paracetamol": "paracetamol",
  "acetaminophen": "paracetamol",
  "voltaren": "diclofenac",
  "diclo": "diclofenac",
  "motrin": "ibuprofen",
  "advil": "ibuprofen",
  "nurofen": "ibuprofen",
  "ibuprofen": "ibuprofen",
  "zithromax": "azithromycin",
  "azithro": "azithromycin",
  "aricept": "donepezil",
  "avlox": "moxifloxacin",
  "avelox": "moxifloxacin",
  "levoxin": "levofloxacin",
  "levaquin": "levofloxacin",
  "piriton": "chlorpheniramine",
  "claritin": "loratadine",
  "cetirizine": "cetirizine",
  "zyrtec": "cetirizine",
  "ctz": "cetirizine",
  "clomid": "clomiphene",
  "benadryl": "diphenhydramine",
  "tab": "tablet",
  "tabs": "tablet",
  "tab.": "tablet",
  "inj": "injection",
  "inj.": "injection",
  "injec": "injection",
  "cap": "capsule",
  "caps": "capsule",
  "cap.": "capsule",
  "syr": "syrup",
  "syr.": "syrup",
  "syrub": "syrup",
  "susp": "suspension",
  "amp": "ampoule",
  "vial": "vial",
  "cream": "cream",
  "ointment": "ointment",
  "soln": "solution",
  "sol": "solution",
  "mg": "milligram",
  "ml": "millilitre",
  "gm": "gram",
  "gr": "gram",
  "pdr": "powder",
  "pdrs": "powder",
  "drp": "drops",
  "drps": "drops",
  "forte": "forte",
  "xr": "extended release",
  "sr": "sustained release",
  "er": "extended release",
  "clav": "clavulanic",
  "cq": "chloroquine",
  "artemether": "artemether",
  "pcm": "paracetamol",
  "apap": "acetaminophen",
  "asa": "aspirin",
  "caf": "caffeine",
  "act": "artemisinin based combination therapy",
  "ats": "anti tetanus serum",
  "acth": "adrenocorticotropic hormone",
  "hct": "hydrochlorothiazide",
  "dxm": "dextromethorphan",
  "dex": "dexamethasone",
  "mtx": "methotrexate",
  "ors": "oral rehydration salts",
  "ivf": "intravenous fluids",
  "ivig": "intravenous immunoglobulin",
  "vitc": "vitamin c",
  "vitd": "vitamin d",
  "inh": "isoniazid",
  "rif": "rifampicin",
  "azt": "zidovudine",
  "nitro": "nitroglycerin",
  "ppi": "proton pump inhibitor",
  "nsaid": "non steroidal anti inflammatory drug",
  "hrt": "hormone replacement therapy",
  "ssri": "selective serotonin reuptake inhibitor",
  "snri": "serotonin norepinephrine reuptake inhibitor",
  "tca": "tricyclic antidepressant",
  "aed": "anti epileptic drug",
  "bzd": "benzodiazepine",
  "cs": "corticosteroid",
  "epo": "erythropoietin",
  "pth": "parathyroid hormone",
  "lhrh": "luteinizing hormone releasing hormone",
  "hgh": "human growth hormone",
  "gcsf": "granulocyte colony stimulating factor",
  "bcp": "birth control pill",
  "ocp": "oral contraceptive pill",
  "rtk": "rapid test kit",
  "fbc": "full blood count",
  "mp": "malaria parasite test",
  "widal": "widal test",
  "pcv": "packed cell volume",
  "urinalysis": "urinalysis",
  "rvs": "retroviral screening",
  "hvs": "high vaginal swab",
  "hvsmcs": "high vaginal swab microscopy culture sensitivity",
  "urinemcs": "urine microscopy culture sensitivity",
  "h.pylori": "helicobacter pylori test",
  "bg": "blood glucose",
  "gt": "glucose tolerance",
  "gtt": "glucose tolerance test",
  "eucr": "electrolytes urea creatinine",
  "lft": "liver function test",
  "lipidprofile": "lipid profile",
  "sfamcs": "seminal fluid analysis microscopy culture sensitivity",
  "esr": "erythrocyte sedimentation rate",
  "cholesterol": "cholesterol",
  "mantoux": "mantoux",
  "mantox": "mantoux test",
  "mcs": "microscopy culture sensitivity",
  "afb": "acid fast bacilli",
  "hbv": "hepatitis b virus",
  "hbvaccine": "hepatitis b vaccine",
  "hcv": "hepatitis c virus",
  "hiv": "human immunodeficiency virus",
  "vdrl": "venereal disease research laboratory",
  "fbs": "fasting blood sugar",
  "rbs": "random blood sugar",
  "ppbs": "post prandial blood sugar",
  "hba1c": "glycated hemoglobin",
  "ppd": "purified protein derivative",
  "hbsag": "hepatitis b surface antigen",
  "hbeag": "hepatitis b e antigen",
  "hcvab": "hepatitis c antibody",
  "hivab": "hiv antibody",
  "hivag": "hiv antigen",
  "att": "anti tuberculo therapy",
  "tb": "tuberculosis",
  "mdrtb": "multi drug resistant tuberculosis",
  "xdrtb": "extensively drug resistant tuberculosis",
  "dots": "directly observed treatment short course",
  "art": "anti retroviral therapy",
  "arv": "anti retroviral",
  "bcg": "bacillus calmette guérin vaccine",
  "dtp": "diphtheria tetanus pertussis vaccine",
  "mmr": "measles mumps rubella vaccine",
  "hpv": "human papillomavirus vaccine",
  "tdap": "tetanus diphtheria pertussis vaccine",
  "acei": "angiotensin converting enzyme inhibitor",
  "arb": "angiotensin receptor blocker",
  "bb": "beta blocker",
  "ccb": "calcium channel blocker",
  "noac": "novel oral anticoagulant",
  "lmwh": "low molecular weight heparin",
  "ufh": "unfractionated heparin",
  "h2ra": "h2 receptor antagonist",
  "tpn": "total parenteral nutrition",
  "ivp": "intravenous push",
  "po": "oral",
  "prn": "as needed",
  "bid": "twice daily",
  "tid": "three times daily",
  "qid": "four times daily",
  "fdc": "fixed dose combination",
  "oha": "oral hypoglycemic agent",
  "glp1": "glucagon like peptide 1 receptor agonist",
  "sglt2i": "sodium glucose cotransporter 2 inhibitor"

}


export default synonyms;